      - name: Build Android APK
        run: |
          # إضافة --include-assets تضمن دمج المانيفست وحل مشكلة الشاشة السوداء
          yes | flet build apk --project "Skynet World AI" --include-assets assets/AndroidManifest.xml
          
